### ISSUE TITLE
Scout the Doggo sizing and reivew

### ISSUE THREAD

**Issue by Lazervike** [tahowallet/dapp#203]
👉  What the assistant/scout will say when. When they transition from one state to another? That can be a pitch or inside the 'beta scope' doc. But you two please confer and then drop here rather than us doing live in a thread. Having that be clear will help everyone.
👉  Where/how we will direct users to Discord or other help resources? (whether in scout or not, that needs to be somewhere)

**Comment by jagodarybacka** [comment]
Stale task
