### ISSUE TITLE
Update banner on the end of season

### ISSUE THREAD

**Issue by kkosiorowska** [tahowallet/dapp#548]
Update the date banner to display end of season information. The banner's design is not yet known. 

Current behaviour 
<img width="688" alt="Screenshot 2023-10-26 at 11 31 26" src="https://github.com/tahowallet/dapp/assets/23117945/1025ef5b-4d3a-45d0-9fcd-e8d1f6afaf49">

**Comment by xpaczka** [comment]
@VladUXUI is this still applicable after change of the UI?

**Comment by VladUXUI** [comment]
we do have a design for, but it just says "0XP", covered in the other ticket
I think we can close this one
