### ISSUE TITLE
Claim flow

### ISSUE THREAD

**Issue by VladUXUI** [tahowallet/dapp#62]
## Flow
- [ ] Landing page / Check eligibility (🛑 Missing narrative)
- [x] Eligibility results
- [x] Agree to Pledge
- [x] Congratz vs Stake? 
We need to define how our claim flow is going to work, to this end i'm going to mock-up a full flow (stake / vote included) and try to get some clarity on the tech side.
- [x] Select council

## Graphics
- [ ] Change graphics to match narrative (🛑 Missing narrative)
- [x] Mobile version
- [ ] Banner with referrals (🛑 Missing narrative)

**Comment by jagodarybacka** [comment]
Stale task
