### ISSUE TITLE
Node Design: Stake / Unstake

### ISSUE THREAD

**Issue by VladUXUI** [tahowallet/dapp#65]
## Figma 
[Link to Staking](https://www.figma.com/file/bEY6fqdX6LiPKP7J1eg7Ag/TokenLaunch-Dapp?type=design&node-id=1652-20858&mode=design&t=QsuA94byhsZ9gSNa-4) (not when claiming)

## Issues
- [ ] [Cooldown/lockdown](https://github.com/tahowallet/dapp/issues/89)
- [x] Screen with warning that you are leaving a node (when you unstake 100%)
- [x] Staking sign tx page
- [x] Staking allow tx

**Comment by jagodarybacka** [comment]
Stale task
