### ISSUE TITLE
Map image is reloaded multiple times

### ISSUE THREAD

**Issue by xpaczka** [tahowallet/dapp#651]
![image](https://github.com/tahowallet/dapp/assets/73061939/ff1b923b-aeae-40c0-a793-02b5418f0ce8)

The map image is being downloaded multiple times, which may cause performance issues (f.e. with the animations). Thing which might cause this behavior 

https://github.com/tahowallet/dapp/blob/66034361a4bf29e99ef4c639570321127d2d16cd/src/ui/Island/IslandRealms.tsx#L12

**Comment by jagodarybacka** [comment]
We ended with conclusion that it is not actually happening because the image is cached (or not) depending on the chrome's settings
