### ISSUE TITLE
Layout not aligned with big amounts of TAHO

### ISSUE THREAD

**Issue by xpaczka** [tahowallet/dapp#665]
![Zrzut ekranu 2023-11-9 o 15 46 39](https://github.com/tahowallet/dapp/assets/73061939/082fb552-462e-4862-8ce7-0e8a961b9546)

I think we should take into consideration that someone will have this big amount of TAHO (low probability, but still), so that inputs and whole layout is always aligned perfectly

@VladUXUI what are your thoughts on it? If it is something that does not bother you, feel free to close this ticket

**Comment by VladUXUI** [comment]
We can drop the amount + TAHO to next line if this is the case.
This is an edgecase so i'm ok if it's not perfect for those users. Also, nobody will have this much :D

**Comment by xpaczka** [comment]
Closing as stated here:
https://github.com/tahowallet/dapp/pull/832#issuecomment-1842996078
