### ISSUE TITLE
LP Staking

### ISSUE THREAD

**Issue by VladUXUI** [tahowallet/dapp#67]
## Figma
[Link to page WIP](https://www.figma.com/file/bEY6fqdX6LiPKP7J1eg7Ag/TokenLaunch-Dapp?type=design&node-id=1941-65122&mode=design&t=QsuA94byhsZ9gSNa-4)

🛑 Blocked by missing documentation / feature pitch?

- [ ] Make it a node with different design style / cover
- [ ] Stake/Unstake
- [ ] Rewards pool [🛑Blocked]
- [ ] Claim rewards
- [ ] Make it clear where to get LP tokens
- [ ] TVL

**Comment by jagodarybacka** [comment]
Stale task
