### ISSUE TITLE
Countdown timer for XP

### ISSUE THREAD

**Issue by Shadowfiend** [tahowallet/dapp#683]
Design is at https://www.figma.com/file/bEY6fqdX6LiPKP7J1eg7Ag/TokenLaunch-Dapp?type=design&node-id=5828-51352&mode=design&t=Q1YXClJU3ZKiq2im-4 .

![image](https://github.com/tahowallet/dapp/assets/8245/1723ce5d-0267-465f-b57c-6c14815189d8)

When the countdown reaches 0, the text should read “XP drop for week X coming soon...” where X is the week number.

**Comment by xpaczka** [comment]
To be resolved in #746
