### ISSUE TITLE
Add basic Realm panel

### ISSUE THREAD

**Issue by xpaczka** [tahowallet/dapp#744]
- [ ] add the panel on the left - can be empty for now
- [ ] make sure it is scrollable
- [ ] make sure top and bottom whitespace is correct
- [ ] make sure it is displayed correctly when user selects the realm

<img width="604" alt="image" src="https://github.com/tahowallet/dapp/assets/20949277/d35d81e7-a7ab-4b25-9194-b8649b0192e9">

**Comment by jagodarybacka** [comment]
Resolved by https://github.com/tahowallet/dapp/pull/774
