### ISSUE TITLE
Add basic Leaderboard panel

### ISSUE THREAD

**Issue by xpaczka** [tahowallet/dapp#745]
Add the panel on the right, can be empty for now. Make sure margins are correct. Make sure we are able to add content above it (countdown component)

<img width="561" alt="image" src="https://github.com/tahowallet/dapp/assets/20949277/0f0e89ed-b974-4c75-8944-05093a5b0c46">

**Comment by jagodarybacka** [comment]
Resolved by https://github.com/tahowallet/dapp/pull/774
