### ISSUE TITLE
Adjust Stake/Unstake section content

### ISSUE THREAD

**Issue by jagodarybacka** [tahowallet/dapp#756]
- [ ] add stake and unstake tabs
- [ ] add tabs content
- [ ] it should be working as it was before - test for regressions
- [ ] adjust styles of inputs, buttons and cooldown component

<img width="1069" alt="image" src="https://github.com/tahowallet/dapp/assets/20949277/4348794a-251c-4ccc-a3ac-a02bbdd2554f">

**Comment by xpaczka** [comment]
Resolves by #786
