### ISSUE TITLE
Realm panel UI issues

### ISSUE THREAD

**Issue by xpaczka** [tahowallet/dapp#784]
UI issues I can see:
- the border above Claimable rewards is different 
Dapp:
![image](https://github.com/tahowallet/dapp/assets/20949277/07c6bb2c-bcb0-406f-88e4-f4925ecd8aa6)
Figma: 
<img width="746" alt="image" src="https://github.com/tahowallet/dapp/assets/20949277/cdf33629-b027-4874-a600-52f5df61ba01">

 - the border looks like it has a shadow? same above the stake banners - in the dapp the separator/border is much more visible than in figma. 

 - lets make sure long names are not messing up the UI 
<img width="746" alt="image" src="https://github.com/tahowallet/dapp/assets/20949277/a6036d9b-ba33-491e-a966-fafc1c60c9ca">

_Originally posted by @jagodarybacka in https://github.com/tahowallet/dapp/pull/777#pullrequestreview-1752559041_

**Comment by jagodarybacka** [comment]
Resolved by https://github.com/tahowallet/dapp/pull/796
