### ISSUE TITLE
Canvas  - drawImage generate 1px border around map

### ISSUE THREAD

**Issue by ioay** [tahowallet/dapp#799]
Canvas  - drawImage generates 1px border around the island map
<img width="507" alt="Screenshot 2023-11-30 at 13 40 59" src="https://github.com/tahowallet/dapp/assets/28560653/e827b68c-10e4-4c89-a21f-a349c2558285">

**Comment by Shadowfiend** [comment]
Let's not let this block release.

**Comment by xpaczka** [comment]
Resolves by #825
